### ISSUE TITLE
你好，请问是否有办法获取2022年以前的数据呢？

### ISSUE THREAD

**Issue by cir-Labo** [panghaibin/COVID-Risk-Region#1]

**Comment by panghaibin** [comment]
后端爬虫的程序在今年年初才开始运行，并且目前官方的接口没有查询历史的功能，故更早以前的数据无法获取。

但是一些地区的疾控公众号会每天发布地区信息，如果不嫌麻烦的话，可以尝试爬他们的公众号。

**Comment by sunbqxyz** [comment]
参考卫健委的数据我爬了一下，可以参考[china_covid_riskareas_history](https://github.com/sunbqxyz/china_covid_riskareas_history)
@panghaibin 也欢迎您直接将数据整合到您的项目中，数据格式上我是参考[RiskLevelAPI](https://github.com/panghaibin/RiskLevelAPI)做的，可能只需要一些小改动。

**Comment by panghaibin** [comment]
@sunbqxyz 感谢提供，稍晚些我会尝试将其进行整合
