### ISSUE TITLE
建议增加一个功能：一步到位查询近N天的风险区

### ISSUE THREAD

**Issue by Mackerly** [panghaibin/COVID-Risk-Region#2]
比如10月1日从广州回到户籍地，户籍地要在7日收到通知说当地有变数，则需要挨个查询7天他返回前是不是高风险区

**Comment by gitoscc** [comment]
我找到一个类似能够查看近期新增的[API接口，带折叠树](https://static-2c1ea984-de3e-488c-9c66-17561bab77a3.bspapp.com/fengxian/)，我觉得可以增加突出显示24小时内（0时后）新增的风险区。N天内的数据量太庞大了，而且风险区随时变化。
